import prisma from "@/libs/prisma";
import { generarRespuesta } from "@/utils/respuestasAlFront";

export async function GET() {
  try {
    const comunas = [
      {
        nombre: "COMUNERO MAYOR MAESTRO ARISTOBULO IZTURIZ",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "1",
      },
      {
        nombre: "COMUNA SOCIALISTA AGRICOLA FRANCISCO DE MIRANDA",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "2",
      },
      {
        nombre: "AGROECOLOGICA LOS TANQUES",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "3",
      },
      {
        nombre: "CUENCA MEDIA ALTA DEL RIO GUARICO",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "4",
      },
      {
        nombre: "COMUNA EZEQUIEL ZAMORA LOS TOQUITOS",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "15",
      },
      {
        nombre: "COMUNA SOCIALISTA NUESTRA SEÑORA DE LAS MERCEDES",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "5",
      },
      {
        nombre: "AGROECOLOGICA SIERRA DEL SUR",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "6",
      },
      {
        nombre: "COMUNA SOCIALISTA MANUELITA SAENZ",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "7",
      },
      {
        nombre: "AGRICOLA VALLES DE TAGUAYGUAY",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "8",
      },
      {
        nombre: "PEDRO CAMEJO",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "9",
      },
      {
        nombre: "7 DE OCTUBRE",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "10",
      },
      {
        nombre: "AGRO-ECOLÓGICA LA VELASQUERA EL CHINO",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "11",
      },
      {
        nombre: "COMUNA JUAN BOLIVAR Y MARTINEZ DE VILLEGAS",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "12",
      },
      {
        nombre: "COMUNA PRODUCTIVA BATALLA DE BOCA CHICA",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "13",
      },
      {
        nombre: "GIGANTE HUGO CHAVEZ",
        id_usuario: 1,
        id_parroquia: 1,
        borrado: false,
        norte: "",
        sur: "",
        este: "",
        oeste: "",
        direccion: "",
        punto: "",
        rif: "14",
      },
    ];

    for (const comuna of comunas) {
      const existente = await prisma.comuna.findFirst({
        where: {
          nombre: comuna.nombre,
          norte: comuna.norte,
          sur: comuna.sur,
          este: comuna.este,
          oeste: comuna.oeste,
          direccion: comuna.direccion,
          punto: comuna.punto,
          rif: comuna.rif,
          borrado: comuna.borrado,
          id_usuario: comuna.id_usuario,
          id_parroquia: comuna.id_parroquia,
        },
      });

      if (!existente) {
        await prisma.comuna.create({ data: comuna });
      } else {
        await prisma.comuna.update({
          where: { id: existente.id },
          data: comuna, // Puedes modificarlo según tu lógica
        });
      }
    }

    return generarRespuesta(
      "ok",
      "comunas creadas o actualizadas correctamente.",
      {},
      201
    );
  } catch (error) {
    console.error("Error al guardar comunas:", error);
    return generarRespuesta(
      "error",
      "Error interno al guardar comunas.",
      {},
      500
    );
  }
}
